### ISSUE TITLE
Dark theme version

### ISSUE THREAD

**Issue by n1zzo** [daniruiz/Flat-Remix-GNOME-theme#4]
Is it possible to have your theme in a dark version?
If you need a hand in making it just tell me!

**Comment by daniruiz** [comment]
At this moment I don't really have much time for it because of the university. But if you could help me it would be great.

**Comment by M4lik** [comment]
I would like to bring that topic up again. For an night time coder like me the light theme is a bit annoying. I would love to contribute to a dark theme, i would even start it. But I have no clue about the css classes and ids that are used. So if you could suggest some kind of doc (haven't found one yet) that I can read myself into this, you could expect a dark version in a not so distant future ;)

Greets from Germany
Malik

**Comment by daniruiz** [comment]
I love the idea of a dark theme, I always wanted to make one but with the university exams I don't have much time. If you help me it would be great :smile:

Well I had the same issue, there is not much documentation out there.
I started modifying other themes by trial and error and little by little it became what it is. I can't help you much. In Gnome you have lg (ALT+F2 -> lg), it will help you inspecting some elements but it isn't much help.
Anyway, as soon as I can I'll port the theme to SASS so that it is easyer to modify.

Maybe you can start with some mockups, and I can find you where to put the code.

**Comment by daniruiz** [comment]
I've been porting part of the css to sass so that some colors can be changed in _colors.scss file. I've just tryed them with some dark values and I think it looks great!
The good new is that with this new version anyone can customice the theme with any other colors.

![captura de pantalla de 2017-10-31 16-20-57](https://user-images.githubusercontent.com/12565871/32232114-9a1c6fc6-be57-11e7-94ae-27f14e7f294b.png)
![image](https://user-images.githubusercontent.com/12565871/32232494-7225c818-be58-11e7-8a17-dc371aca3ddf.png)
![image](https://user-images.githubusercontent.com/12565871/32232523-82169af4-be58-11e7-9dcc-f3f95fb5a0f6.png)

**Comment by M4lik** [comment]
ok, the port to sass solves a lot of issues. ^^
and the dark colors make it almost perfect. 👍 nice work

**Comment by daniruiz** [comment]
I've updated a beta of the dark theme and a dark theme with miami dark color scheme, if you want to try it
